### ISSUE TITLE
https connections do not time out

### ISSUE THREAD

**Issue by schnoddelbotz** [contentstack/contentstack-python#12]
In 0.1.0, there was a static timeout on requests:
https://github.com/contentstack/contentstack-python/blob/ed273e08256ec51887db2adf854b2aa40759e554/contentstack/http_connection.py#L55

In 1.0.0+ ... it was lost?
https://github.com/contentstack/contentstack-python/blob/v1.1.0/contentstack/https_connection.py#L57
The doc strings sound as if the timeout was consumed somewhere ... but it isn't?
This will make the client hang forever (requests' default) in case of network issues.

Also, it would be nice if the client supported retries ( https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.retry ), ideally with sane defaults that can be overridden by users.

**Comment by ishaileshmishra** [comment]
Thanks @schnoddelbotz for raising the issue. We’re looking into it and we’ll push a fix as early as possible.
