### ISSUE TITLE
`Stack.sync_init` uses wrong parameter names

### ISSUE THREAD

**Issue by aeons** [contentstack/contentstack-python#17]
https://github.com/contentstack/contentstack-python/blob/056126641f4823a006abf3016017a7bddef9076b/contentstack/stack.py#L194-L199

`from_date` should be `start_from` and `publish_type` should be `type` per https://www.contentstack.com/docs/developers/apis/content-delivery-api/#initial-sync

**Comment by ishaileshmishra** [comment]
Thanks for creating the issue. We will look into it and update you once done. @aeons

**Comment by ishaileshmishra** [comment]
the issue has been fixed, thanks
