### ISSUE TITLE
Include Reference Functionality Not Complete

### ISSUE THREAD

**Issue by jmheldsans** [contentstack/contentstack-python#9]
https://github.com/contentstack/contentstack-python/blob/cc35b436df3e22738f437b2849931cc015ea404e/contentstack/entryqueryable.py#L79-L105

This function doesn't appear to support including multiple references in a query.

https://www.contentstack.com/docs/developers/apis/content-delivery-api/#include-reference

The API docs require multiple references to be included as follows:

```
https://cdn.contentstack.io/v3/content_types/product/entries?include[]=categories&include[]=brands
```

But it seems like:

```
self.entry_queryable_param["include[]"] = reference_field_uid
```

Having self.entry_queryable_param defined as a dict would limit the "include[]" key to only one value, especially as used with parse.urlencode.

```encoded_string = parse.urlencode(self.query_params, doseq=True)```

Am I looking at this wrong?  Is there another way to include multiple references that I am not seeing?

**Comment by jwaterbury26** [comment]
@contentstack-admin any update on this?

**Comment by ishaileshmishra** [comment]
Hi @jwaterbury26, we will look into this and get back to you soon
